### ISSUE TITLE
Annotation properties to list of values rather than individual values

### ISSUE THREAD

**Issue by matentzn** [luis-gonzalez-m/Collembola#2]
Annotations such as:

```
<webprotege:RDVJMEwZYIoh2aGNk8xeN3s>linea ventralis
labial vental groove
ventral line
mediolongitudinal groove
ventral nephridial channel</webprotege:RDVJMEwZYIoh2aGNk8xeN3s>
```

(aside from using the wrong property, see #1 )

should look something like:

```
<webprotege:RDVJMEwZYIoh2aGNk8xeN3s>linea ventralis</webprotege:RDVJMEwZYIoh2aGNk8xeN3s>
<webprotege:RDVJMEwZYIoh2aGNk8xeN3s>labial vental groove</webprotege:RDVJMEwZYIoh2aGNk8xeN3s>
<webprotege:RDVJMEwZYIoh2aGNk8xeN3s>ventral line</webprotege:RDVJMEwZYIoh2aGNk8xeN3s>
<webprotege:RDVJMEwZYIoh2aGNk8xeN3s>mediolongitudinal groove</webprotege:RDVJMEwZYIoh2aGNk8xeN3s>
<webprotege:RDVJMEwZYIoh2aGNk8xeN3s>ventral nephridial channel</webprotege:RDVJMEwZYIoh2aGNk8xeN3s>
```

For each individual value, a separate assertion!

**Comment by luis-gonzalez-m** [comment]
Hello, annotations properties (has_related_synonym) were checked. I will upload the new ontology.   Thank you.

**Comment by matentzn** [comment]
Good job, still some left:

https://github.com/luis-gonzalez-m/Collembola/blob/3a991c470c781483e388d94f8c0905c9674763ff/Collembola%20Anatomy%20Ontology.owl#L471

https://github.com/luis-gonzalez-m/Collembola/blob/3a991c470c781483e388d94f8c0905c9674763ff/Collembola%20Anatomy%20Ontology.owl#L2724

Are you handy with regular expressions?

```
Synonym>[a-zA-Z ]+\n
```

If you search for this in your ontology (as a textile, say in the editor Atom, or Notepad++) you get about forty hits, like, for example:

http://purl.obolibrary.org/obo/CLAO_0000280
http://purl.obolibrary.org/obo/CLAO_0000317
http://purl.obolibrary.org/obo/CLAO_0000854
http://purl.obolibrary.org/obo/CLAO_0000914

In case you need help to track them down I attached a version of clao which has the word |BROKEN| wherever there is (or was) a property like that. Let me know if you need more help!

[clao.txt](https://github.com/luis-gonzalez-m/Collembola/files/4897155/clao.txt)

**Comment by luis-gonzalez-m** [comment]
Hi, sorry, I thought all synonyms were corrected but I already checked them. I'll upload the file.

**Comment by luis-gonzalez-m** [comment]
Hi,

An user has observed that the link http://api.hymao.org/api/ref/67791 and similar mentioned by HAO (Hymenotera Anatomy Ontology) are invalid currently, which these are part of annotations in this ontology.My question is how fix it? simply is ommitted or this change must be made in the ontology HAO?. What is the next step or correction for my ontology CLAO?  Thank you

**Comment by matentzn** [comment]
I think its best this is recorded here: https://github.com/hymao/hao/issues

Regarding your ontology, there is at least https://github.com/luis-gonzalez-m/Collembola/issues/3

Then it goes back to the OBO review

**Comment by luis-gonzalez-m** [comment]
Hi, I checked ontology again. Thank you.

**Comment by matentzn** [comment]
Good job, its fine now!
